name: condaenv
channels:
  - conda-forge
dependencies:
  - albumentations=1.0.3
  - geos=3.9.1
  - geotiff=1.6.0
  - h5py=2.10.0
  - imageio=2.9.0
  - loguru=0.5.3
  - mkl=2020.4
  - numpy=1.21.1
  - pandas=1.3.1
  - pillow=8.2.0
  - pip=20.3.4
  - pydantic=1.8.2
  - pydap=3.2.2
  - pyepsg=0.4.0
  - pygeos=0.10.1
  - pytest=6.2.4
  - python=3.9.6
  - rasterio=1.2.6
  - scikit-image=0.18.2
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - shapely=1.7.1
  - tensorflow=2.4.1
  - tifffile=2021.8.8
  - tiledb=2.3.2
  - tqdm=4.62.0
  - typer=0.3.2
  - xarray=0.19.0
  - pip:
    - -f https://download.pytorch.org/whl/torch_stable.html
    - fastai==2.5.0
    - ttach==0.0.3
    - segmentation-models-pytorch==0.2.0
    - pytorch-lightning==1.4.1
    - timm==0.4.12
    - torch==1.9.0+cpu
    - torchvision==0.10.0+cpu